gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# Site settings
author:
  name: Jacob Liljehult
  image: https://jacobliljehult.github.io/neuro/images/brainicon.png
  email: jacob.mesot.liljehult@regionh.dk
description: "Jacob Liljehult"
locale: da_DK
logo: https://jacobliljehult.github.io/neuro/images/brainicon.png

# Build setting
